# Generated by Django 5.0.4 on 2024-05-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.basemodel')),
                ('email', models.EmailField(max_length=150)),
                ('message', models.TextField()),
            ],
            bases=('product.basemodel',),
        ),
        migrations.CreateModel(
            name='ProductBottles',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.basemodel')),
                ('bottle_size_ml', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount_percent', models.IntegerField(default=0)),
            ],
            bases=('product.basemodel',),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.basemodel')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            bases=('product.basemodel',),
        ),
        migrations.CreateModel(
            name='ComboProducts',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.basemodel')),
                ('name', models.CharField(max_length=150)),
                ('discription', models.TextField(blank=True, null=True)),
                ('discounted_price', models.IntegerField()),
                ('bottles', models.ManyToManyField(related_name='included_combo_offers', to='product.productbottles')),
                ('free_bottles', models.ManyToManyField(related_name='included_free_bottles_combo', to='product.productbottles')),
            ],
            bases=('product.basemodel',),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.basemodel')),
                ('image', models.ImageField(upload_to='product_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.products')),
            ],
            bases=('product.basemodel',),
        ),
        migrations.AddField(
            model_name='productbottles',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottles', to='product.products'),
        ),
    ]
