# Generated by Django 5.0.4 on 2024-08-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_comboproducts_free_bottles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboproducts',
            name='free_bottles',
            field=models.ManyToManyField(blank=True, related_name='included_free_bottles_combo', to='product.productbottles'),
        ),
    ]
